### ISSUE TITLE
How `pipx` differs from `pipsi`?

### ISSUE THREAD

**Issue by castarco** [cs01/pipx#1]
It would be nice to include documentation/information about how `pipx` differs from `pipsi`...

**Comment by cs01** [comment]
Thanks, I added a section at the bottom of the readme.

**Comment by kwill** [comment]
This is helpful! Could you also add a comparison to https://github.com/jaraco/rwt ? My quick assessment is that RWT handles dependency loading in multiple scenarios, *including* running a module binary directly from PyPI, whereas pipx is *focused* on that use-case and can therefore provide simpler invocations.

**Comment by cs01** [comment]
@kwill that is exactly right. 

pipx also allows you to install to the filesystem permanently, whereas RWT only works in ephemeral environments.
