### ISSUE TITLE
Respect entry_points.txt

### ISSUE THREAD

**Issue by neersighted** [cs01/pipx#10]
Currently pipx does not discover scripts from `entry_points.txt`. This means it is unable to install packages like `asciinema`, `autopep8`, `pylint`, and `python-language-server`.

pipsi has an example of how to parse this metadata here: https://github.com/mitsuhiko/pipsi/blob/master/pipsi/scripts/find_scripts.py

**Comment by cs01** [comment]
Thank you, I’ll take a look at this and add it.

**Comment by cs01** [comment]
I was able to install each of these with pipx. For example

```
>> pipx install autopep8
autopep8 from package autopep8 is now available globally
done! ✨ 🌟 ✨
```

pipx iterates over entrypoints with [this](https://github.com/cs01/pipx/blob/master/pipx/main.py#L117)
```
for _, d in pkg_resources.get_entry_map(dist).items():
    for binary in d:
        print(binary)
        binaries.add(binary)
```

**Comment by cs01** [comment]
Standby, I had slightly different code running on my machine.

**Comment by cs01** [comment]
This should be fixed on master. To upgrade run
```
pipx upgrade pipx
```

**Comment by neersighted** [comment]
This appears to fix the issues for me; might be useful to leave this open however, just in case parsing entry_points.txt allows discovery of additional binaries.

**Comment by neersighted** [comment]
It appears that `pkg_resources` internally parses entry_points.txt (which is specified and stable, but this is a nicer frontend to the file). Since the latest version of pip/setuptools should always be installed in pipx-managed virtual environments, I think this issue is resolved.

**Comment by cs01** [comment]
Thanks for looking into this, it helps make the tool better for everyone. @aiguofer recently modified that code to be a little more strict in which sections are used. https://github.com/cs01/pipx/pull/28/files
