### ISSUE TITLE
Cannot install mssql-cli

### ISSUE THREAD

**Issue by petobens** [cs01/pipx#12]
I don't know if this is something with my setup or what but if I run 
```
pip install mssql-cli
```
and then run `mssql-cli --version` then everything is fine. On the other hand if i run 
```
pip uninstall mssql-cli
pipx install mssql-cli
```
and re-run `mssql-cli --version` I get
```
/usr/bin/python: Error while finding module specification for 'mssqlcli.main' (ModuleNotFoundError: No module named 'mssqlcli')
```
I'm using python 3.7. Thanks in advance for looking into this.

**Comment by petobens** [comment]
The referenced commit doesn't fix my issue. It should've?

**Comment by cs01** [comment]
It turns out the issue is with the `mssqli-cli` library itself. I created an [issue](https://github.com/dbcli/mssql-cli/issues/227) and a [pull request](https://github.com/dbcli/mssql-cli/pull/228) to fix it.

If you want to install now with the fix, you can install from my [branch](https://github.com/cs01/mssql-cli) with the fix. 
```
pipx install --spec git+https://github.com/cs01/mssql-cli@593d7f6516 mssql-cli
```
Note that this method does a git clone of the repository, which unfortunately takes a while, but I did confirm that it works.
```
mssql-cli.bat from package mssql-cli is now available globally
mssql-cli from package mssql-cli is now available globally
done! ✨ 🌟 ✨
>> mssql-cli
Username (press enter for sa):
```

**Comment by petobens** [comment]
Wowwww, that's an awesome and unseen level of support! Thank you so much :)

**Comment by cs01** [comment]
Tell your friends!

**Comment by shawnohare** [comment]
I just wanted to note for others coming across this issue that the aforementioned PR has been merged, but the current `mssql-cli v0.15.0` does not include them, so one should still install from @cs01's branch or master.

**Comment by petobens** [comment]
@shawnohare does installing from master work for you? See https://github.com/dbcli/mssql-cli/issues/247

**Comment by shawnohare** [comment]
No, for the exact reason listed in your link. I suppose I was a bit hasty in suggesting the master branch worked, sorry for the confusion!

**Comment by nickolay** [comment]
The fix to mssql-cli has been reverted, and the original problem is back: https://github.com/dbcli/mssql-cli/issues/496
