### ISSUE TITLE
Expected to find pip at /home/<user>/.local/pipx/venvs/<pkg>/bin/pip

### ISSUE THREAD

**Issue by aiguofer** [cs01/pipx#16]
Hi, I just installed pipx using:

```
curl -sL https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | PYENV_VERSION=system python3
```

I'm my system Python 3 is 3.7.0 in case that matters, and I'm also using Pyenv.

When I install packages `pipx install <pkg>`, I get the following error:
```
Expected to find pip at /home/<user>/.local/pipx/venvs/<pkg>/bin/pip
```

**Comment by cs01** [comment]
pipx creates a virtual environment with 
```
python3 -m venv <path to venv>
```
then assumes
```
<path to venv>/bin/pip
```
exists. Looks like for some reason it doesn't. It might have something to do with pyenv. Could you paste the output of 
```
ls  /home/<user>/.local/pipx/venvs/<pkg>/bin/
```

You might want to try 
```
pipx install --python PYTHON <pkg>
```
with the exact path to the python you want, just to see if that helps.

**Comment by cs01** [comment]
According to the pip documentation, it should exist. https://pip.pypa.io/en/stable/installing/#do-i-need-to-install-pip

**Comment by cs01** [comment]
> It seems like a different issue though, if you want to close this one I can open one up for general issues with pyenv

Agreed, sounds good. 

`pipx` *could* write that symlink, but I stopped it from doing so because then you'd have multiple binaries with the same name on your path, and that would be confusing. If you remove `/home/rdu/difernan/.local/bin/` from your PATH, or remove `/home/rdu/difernan/.local/bin/black`, then pipx will make the symlink for you.

**Comment by cs01** [comment]
Closing this issue, let me know how your progress goes w/ pyenv.
