### ISSUE TITLE
`pipx` name on PyPI is taken by another project

### ISSUE THREAD

**Issue by cs01** [cs01/pipx#2]
<s>
I spoke with the owner of the `pipx` name on PyPI about transferring ownership to this project, and he said he would do so only if it was popular enough.

**Add a thumbs up to this issue to signal to the owner that you would like this project to be transferred as the owner of the name on PyPI.**

* [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) is the node package runner, so for symmetry it makes sense that pipx would be the Python package runner
* if ownership was transferred, I would add a section in the README thanking him and linking to his github projects
</s>

*thank you for all the upvotes!*

Update: The owner of the pipx name is going to keep the name. This issue is now to determine the best way forward in terms of installing `pipx` and choosing a name (if any) on PyPI.

**Comment by r-darwish** [comment]
I think that in the meantime it should be stated in the README that pipx in PyPi isn't this project.

**Comment by cs01** [comment]
@r-darwish added a note

**Comment by lgw4** [comment]
I agree with @simonw (but I suggest `python-pipx` as the temporary package name).

**Comment by ludbek** [comment]
> I spoke with the owner of the pipx name on PyPI about transferring ownership to this project, and he said he would do so only if it was popular enough.

The exact words were, "I would have transferred the ownership if the tool had been used by lots of users. 
I will have to reserve the package ownership.

Hope you get a better name."

>  Is there a star count or like count that you require to transfer ownership? Would the link in pipsi's README convince you?

It's not the stars or likes that I count, I just wanted to make sure that the package won't be abandoned at some point (again).

> npx is the node package runner, so for symmetry it makes sense that pipx would be the Python package runner

I would suggest not to follow node. I wanted `pipx` to be similar to npm and now I have realized that it was a mistake. I should have stayed with `pip` convention.

**Comment by cs01** [comment]
Based on your comments of transferring ownership if it had "lots of users" and asking to have "my profile somewhere visible in the readme file (not in obscure way)" it seemed like it was in your interest to promote your work on a project with lots of traffic; I was trying to make that happen for you. pipsi and your pipx package are both unmaintained so I don't understand your statement about abandoned packages, but regardless I'll move forward with a different solution.

**Comment by cs01** [comment]
> so people can start installing and trying out the app without having to curl / pipe.

The `get-pipx.py` script does a few things differently than a regular `pip install`:

* Creates a new virtual environment in `~/.local/pipx/venvs/pipx`
* Installs pipx in that virtual env
* Symlinks the pipx binary to `~/.local/bin`
* Ensures `~/.local/bin` is on your path

As opposed to a regular pip install:
* installs package to `site-packages` directory of the python executable used to install
* creates binaries in `bin` directory of the python executable used to install

If the bootstrap instructions change to just `pip install pipx-app` or `python-pipx`, the bootstrap instructions would need to have a bunch of manual steps added to do the things `get-pipx..py` do like create a virtual env, add to your PATH, etc. 

(After that, the `pipx upgrade pipx-app` or `pipx upgrade python-pipx` would work fine though.)

So given that the bootstrap process would be less smooth/more tedious if switched to a PyPI package, I am inclined to leave the instructions pointing to the git repository (unless I am missing something).

**Comment by ludbek** [comment]
> I think it would be really cool if pipsi could rename itself to pipx. Is there any chance you'd be willing to hand ownership of pipx over to the pipsi project? If you did we'd add a section in the README giving thanks to you and linking to your github profile which would get you more visibility.

It was your call. Whats wrong for asking it to do properly?

> pipsi and your pipx package are both unmaintained so I don't understand your statement about abandoned packages

`It's not the stars or likes that I count, I just wanted to make sure that the package won't be abandoned at some point (again).`

The statement has `again` in it.

**Comment by cs01** [comment]
@simonw @lgw4 I'm going to close this issue. If you have any other thoughts on my comment (https://github.com/cs01/pipx/issues/2#issuecomment-434747085) please create a new issue. I realize requiring curl is a non-standard way of installing things, but then again pipx is not supposed to be installed like other packages.

**Comment by cs01** [comment]
> For the moment I suggest using a name like pipx-app so people can start installing and trying out the app without having to curl / pipe.

pipx is now on PyPI as `pipx-app`
