### ISSUE TITLE
pipx install ansible - No binaries associated with this package.

### ISSUE THREAD

**Issue by sahensley** [cs01/pipx#20]
First off, thanks again for making pipx!

Installing [Ansible](https://github.com/ansible/ansible) with pipx fails with "no binaries associated with this package".  

Ansible is packaged in a fairly unique manner, as can be seen in the [setup.py](https://github.com/ansible/ansible/blob/devel/setup.py) file and examining the [bin folder](https://github.com/ansible/ansible/tree/devel/bin).  The main binary is `ansible` and other functionality such as `ansible-playbook` is a symlink to `ansible`.

I wouldn't expect this to be a quick fix but I did want to note this in an issue.

**Comment by cs01** [comment]
This should be fixed in v0.0.0.13.

**Comment by sahensley** [comment]
I updated and it works great - thank you.  You are absolutely killin' it with this project!  

I'll be closing the Pipsi issue for additional maintainers soon.  I'm hoping one of the maintainers is willing to put in a note on the main readme that Pipsi is essentially not maintained and a link to alternatives, such as Pipx.

**Comment by cs01** [comment]
Thanks that is really good to hear, especially from you. That issue you made was actually the motivation for me staring this project. I love the concept of pipsi, but it wasn't working for me with python3 (it couldn't create virtualenvs for some reason) and I wanted to keep the momentum going somehow. I wasn't sure how pipx would be received by the community but it seems like so far so good.

**Comment by pdecat** [comment]
For people coming here from Google like me, ansible now needs to be installed by `pipx install ansible-base`:

```
# pipx --version
```
```
# pipx install ansible
Note: Dependent package 'ansible-base<2.11,>=2.10.1' contains 11 apps
  - ansible
  - ansible-config
  - ansible-connection
  - ansible-console
  - ansible-doc
  - ansible-galaxy
  - ansible-inventory
  - ansible-playbook
  - ansible-pull
  - ansible-test
  - ansible-vault

No apps associated with package ansible. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```
```
# pipx install ansible-base
  installed package ansible-base 2.10.2, Python 3.8.5
  These apps are now globally available
    - ansible
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
done! ✨ 🌟 ✨
```

Related: https://github.com/pipxproject/pipx/issues/504

**Comment by markasbach** [comment]
> And if you need [community modules and plugins which are now part of collections](https://github.com/ansible-collections/overview#now-ansible-2-10-and-later), you can then inject them:

Great tip. It seems, there's a typo in the syntax, though. If `ansible-base` has been installed, I assume the correct command would be injecting `ansible` into the `ansible-base` virtual environment, so it should read:

    pipx inject ansible-base ansible

**Comment by alorence** [comment]
As an alternative, you can install `ansible` with option `--include-deps` to ensure binaries from dependent package (i.e. `ansible-base`) will be setup as globally available commands. This is a 1-line alternative to the solution provided by @pdecat 

```bash
❯ pipx install --include-deps ansible
  installed package ansible 6.6.0, installed using Python 3.10.8
  These apps are now globally available
    - ansible
    - ansible-community
    - ansible-config
    - ansible-connection
    - ansible-console
    - ansible-doc
    - ansible-galaxy
    - ansible-inventory
    - ansible-playbook
    - ansible-pull
    - ansible-test
    - ansible-vault
done! ✨ 🌟 ✨

❯ ansible --version
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/home/alorence/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alorence/.local/pipx/venvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/alorence/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/alorence/.local/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by MurtadhaInit** [comment]
Can confirm that `pipx install --include-deps ansible` works fine for me.

Using `pipx install ansible` will _only_ add the `ansible-community` binary into the bin folder (making it accessible to $path) and not the other binaries (like the `ansible` command).
