### ISSUE TITLE
Documentation wording

### ISSUE THREAD

**Issue by willsALMANJ** [cs01/pipx#21]
The README is misleading regarding what is added to the path:

```
The install command is the preferred way to globally install binaries from python packages on your system. It creates an isolated virtual environment for the package, then in a folder on your PATH creates symlinks to all the binaries in that virtual environment.
```

`pipx` does not create symlinks to all the binaries in the virtual environment, rather to all the binaries provided by the installed package (not any installed by its dependencies).

Also, I find the use of "binary" in the README misleading. Really, what are added to the path are executable files, typically Python scripts, not binary files.

**Comment by cs01** [comment]
Thanks for the suggestions! I updated the text per your comments. Let me know what you think about the new text.

**Comment by willsALMANJ** [comment]
Looks good! I was going to point out "localed" but you already fixed it.
