### ISSUE TITLE
Allow adding files to the path even when already on the path

### ISSUE THREAD

**Issue by willsALMANJ** [cs01/pipx#22]
Right now, if you try to install a package already installed on the system, you get a message like this: `flake8 is already on your PATH at /usr/bin/flake8. Not creating new symlink ...` It should be possible (perhaps default?) to install the symlink any way (assuming there is no file at the symlink target already, other than a pipx symlink) because perhaps the package needs to be installed for the system but I want to put a newer version in front of it on my user's path. It is nice to show a warning, perhaps even checking after install if the installed version is first on the path.

**Comment by aiguofer** [comment]
Related to #17

**Comment by cs01** [comment]
I updated the logic to create the symlink even if a binary is already on the path.
```
pipx install black
black from package black is now available globally
⚠️  Note: black was already on your PATH at /opt/bin/black
blackd from package black is now available globally
done! ✨ 🌟 ✨
```

**Comment by sudoshindo** [comment]
Is there no option/flag for `install` to set a custom symlink name?

```
$ which rename
/home/shindo/.local/bin/rename # pipx/python
/usr/bin/rename
```

Yes, manually making renaming the symlink or making a separate one is an option.
I'm just curious if pipx doesn't have anything built-in to handle it.
