### ISSUE TITLE
Conda support?

### ISSUE THREAD

**Issue by willsALMANJ** [cs01/pipx#29]
Is there any way to support conda packages? I am guessing that "pipx for conda" is an easy analogy to make but in practice there would be little code re-use between the pip and conda versions. So I'm not saying this should be added to pipx, but I thought there could at least be a closed issue about conda in the issue tracker for future reference.

A conda equivalent would be nice to have. If anyone knows of one or writes one, link to it here for future reference.

**Comment by cs01** [comment]
I am not a conda user. Based on your description it sounds like pipx in its current form won't work for conda. Thanks for filing the issue though. I agree it makes sense for documentation/tracking purposes.

**Comment by willsALMANJ** [comment]
Thanks, I will close this now. If I ever find the time, I might try translating pipx for conda. I think almost all the same actions are possible with conda as with pip and it is mainly a matter of translating the API's.

**Comment by ackalker** [comment]
@wshanks 
There is a [`condax` package](https://pypi.org/project/condax/#description) on PyPI, which is somewhat similar in intention (but not in code) to `pipx`, but for Anaconda packages.
