### ISSUE TITLE
identify more binary definitions 

### ISSUE THREAD

**Issue by Zelgius** [cs01/pipx#3]
It appears that currently pipx doesn't support installing packages that don't have a binary associated with them.  One said tool that I used pipsi to install and would like to use pipx to install would be the awscli

```
[14:14:43] megger:~ $ pipx install awscli
No binaries associated with this package
```

Is there any plans to support this type of installation?

**Comment by cs01** [comment]
OK this should be fixed. You can give it a try with
```
pipx update awscli
```
Let me know how it goes. Thanks!

**Comment by cs01** [comment]
I'm going to close. If it's still not working add another comment and I'll take a look.

**Comment by ptink** [comment]
```
pt@pt-laptop:~$ pipx --version
0.12.0.4
pt@pt-laptop:~$ pipx install awscli
Note: Dependent package 'rsa<=3.5.0,>=3.1.2' contains 8 binaries
  - pyrsa-sign
  - pyrsa-priv2pub
  - pyrsa-decrypt-bigfile
  - pyrsa-encrypt-bigfile
  - pyrsa-verify
  - pyrsa-keygen
  - pyrsa-encrypt
  - pyrsa-decrypt
No binaries associated with package awscli.
pt@pt-laptop:~$ ls -la /home/pt/.local/pipx/venvs/
total 8
drwxr-xr-x 3 pt pt 4096 Feb 11 09:02 .
drwxr-xr-x 3 pt pt 4096 Feb  4 10:23 ..
```

Am I missing anything?

**Comment by cs01** [comment]
Thanks for filing, I just confirmed this no longer works. I filed a new issue to work on this. https://github.com/pipxproject/pipx/issues/91
