### ISSUE TITLE
shell-functools does not detect binaries

### ISSUE THREAD

**Issue by neersighted** [cs01/pipx#33]
https://github.com/sharkdp/shell-functools

This issue appears to be identical to #20... Looking at the setup.py for ansible and shell-functools, both use `scripts=[]` instead of `entry_points`.

**Comment by cs01** [comment]
This should be fixed in v0.0.0.13.

**Comment by cs01** [comment]
shell-functools is cool, by the way

**Comment by neersighted** [comment]
Excellent work! Everything appears to be working now.
