### ISSUE TITLE
Issue when name of package isn't the name of executable

### ISSUE THREAD

**Issue by Zelgius** [cs01/pipx#35]
When trying to use just a one shot of the awscli pipx fails since the command you get when you install awscli is `aws` not `awscli`. Maybe have an option where you can specify --opt-cmd to allow you to change the command being passed in?

```
root@efceac62900a:/# pipx awscli
awscli not found in package awscli. Available binaries: aws, aws.cmd, aws_bash_completer, aws_completer, aws_zsh_completer.sh
```

**Comment by cs01** [comment]
That is what the `--spec` argument is for.

```
pipx --spec awscli aws
```
