### ISSUE TITLE
Don't reinstall if already installed

### ISSUE THREAD

**Issue by petobens** [cs01/pipx#37]
Hi! I if a binary is already installed, such as black, and I run:
```
pipx install black --verbose
```
this will reinstall black. Can this be avoid and instead give a message saying "Black is already installed, nothing to do" or something like that. Thanks!

**Comment by cs01** [comment]
I think this came up before, and I think your suggestion makes sense. I can make that change and add an optional `--overwrite` flag that overwrites whatever is there.

**Comment by cs01** [comment]
This has been added in 0.10.3.0.

```
>> pipx install pipx-app
Not installing to existing directory '/Users/user/.local/pipx/venvs/pipx-app'. Pass '--force' to force installation
```

**Comment by petobens** [comment]
Thank you :)
