### ISSUE TITLE
blackd

### ISSUE THREAD

**Issue by jgirardet** [cs01/pipx#46]
hi,
```pipx install black``` does not install aiohttp needed by blackd.

how do you deal with it ?

nice tool.
Jimmy

**Comment by cs01** [comment]
Similar to the regular pip install of black, the extras are not there unless specified. In this case, the extra is `extras_require={"d": ["aiohttp>=3.3.2"]},`, so you would do

```
pipx install black --spec black[d] --force
```

There is also a PR attempting to add dependencies to a package's venv on a case-by-case basis: https://github.com/cs01/pipx/pull/45. LMK which approach you like more.

**Comment by jgirardet** [comment]
ok cool

**Comment by mandrean** [comment]
For anyone coming here in 2020, I had to run a slightly different command because the CLI probably changed a bit:

```
$ pipx install "black[d]" --force
```
