### ISSUE TITLE
Support passing --index-url to pip install command

### ISSUE THREAD

**Issue by DanCardin** [cs01/pipx#47]
In writing this, it turns out I can do `pipx install --spec https://custompypi.com/api/pypi/pypi/packages/examplepackage/1.0.0 binary`, but it'd be nice if the interface was more normal to how installation would typically work

```
pipx install --index-url https://custompypi.com/api/pypi/pypi/simple binary
pipx install --index-url https://custompypi.com/api/pypi/pypi/simple --spec examplepackage==1.0.0 binary
```

**Comment by cs01** [comment]
Nice, I can add this.

**Comment by cs01** [comment]
This has been added in pipx-app 0.10.4.0.
