### ISSUE TITLE
Moving from pipsi?

### ISSUE THREAD

**Issue by naiveai** [cs01/pipx#48]
Is there a guide on how to move your binaries to pipx after using pipsi?

**Comment by cs01** [comment]
There is not. And there is unfortunately no automated way to do this, so you will have to remove pipsi's directory completely then reinstall everything with pipx.

If you do
```
rm -r ~/.local/pipsi
```
there will still be symlinks in `~/.local/bin` that point to `~/.local/pipsi/venvs`. But if you reinstall the same packages with `pipx`, they symlinks will be overwritten with valid symlinks that point to the `pipx` directory.

 I will add a section in the README about this, good call.

**Comment by cs01** [comment]
This has been added in pipx-app 0.10.4.0.
