### ISSUE TITLE
Emojis don't work

### ISSUE THREAD

**Issue by tkossak** [cs01/pipx#5]
Is there a global option to turn them off?

![image](https://user-images.githubusercontent.com/3728245/47257317-7c41d800-d48c-11e8-8281-b5b97034385e.png)

I use pipx 0.0.0.5 / fish 2.7.1 / tmux 2.8 / xfce4-terminal 0.8.7.4

**Comment by cs01** [comment]
There's not but it looks like I should figure out how to handle this better. Thanks for reporting.

**Comment by cs01** [comment]
Looks like the solution here is for the end user to fix or work around the issue in their terminal since pipx is outputting valid unicode characters. Maybe update your terminal?

See also
https://github.com/ambv/black/issues/223

**Comment by cs01** [comment]
I added explicit encoding metadata at the top of the file which might help. Try running
```
pipx upgrade pipx
```
(the version is still 0.0.0.6)

**Comment by tkossak** [comment]
No change for me, fish still displays raw values. Maybe my xfce4-terminal or tmux doesn't support any emojis.

![image](https://user-images.githubusercontent.com/3728245/47257830-0c831b80-d493-11e8-8a8a-fa2414395d74.png)

btw. the version changed from 0.0.0.5 to 0.0.0.6.

**Comment by cs01** [comment]
I use tmux, bash, and iterm2, and they work fine in it. It must be either fish or xfce4-terminal.

**Comment by tkossak** [comment]
xfce4-terminal probably. I just run it with only bash inside, and see the same raw characters.
