### ISSUE TITLE
Need option '--editable' for pipx-install

### ISSUE THREAD

**Issue by kannanmr** [cs01/pipx#50]
I recently switched to pipx from pipsi. So far, it is reliable and intuitive, love it. 

Is there an equivalent to 'pipsi install --editable'? If not, IMO, it'd be a great addition.

**Comment by cs01** [comment]
Glad you are liking it!

You can do
```
pipx install PACKAGE --spec PATH_OR_URL
```

but it won't reflect local changes. I am curious what your workflow is here, could you describe it a little?

**Comment by kannanmr** [comment]
I use your snippet to install the local folder, yes. 

For my team, I always enable 2 flows --
`make install` For deploy testing. 
`make develop` for dev testing. When we were using `pipsi`, I just did `pipsi --editable .` and this setup the package & the symlink, but the developer always had the luxury of quickly making changes to the source code, and retesting with out `make install` again and again.

**Comment by kannanmr** [comment]
I took a look at pipx code, I think the only addition needed is to add an option `--develop` and propagate it to `venv`, so `_run_pip()` can append `--editable` before handing over to `subprocess.run()`?

**Comment by cs01** [comment]
> I took a look at pipx code, I think the only addition needed is to add an option --develop and propagate it to venv, so _run_pip() can append --editable before handing over to subprocess.run()?

Yup that sounds right!

> When we were using pipsi, I just did pipsi --editable . 

I am guessing pipsi gets the package name by running `python setup.py --name`. pipx doesn't do that; it requires you to pass the package name. Maybe that will be another change to make.

**Comment by cs01** [comment]
This has been added in pipx-app 0.10.4.0.

**Comment by schlamar** [comment]
If anybody else wonders how to use this, the following command works for the local directory:

```
pipx install --editable .
```
