### ISSUE TITLE
pipx is impacted by current dir?

### ISSUE THREAD

**Issue by pawamoy** [cs01/pipx#57]
When I run `pipx` in one of my directories (Python project), `pipx` outputs some error messages about dependencies, when it should not:

```console
$ pipx ipython
⚠️  ipython is already on your PATH and installed at /home/pawamoy/.local/bin/ipython. Downloading and running anyway.
aria2p 0.1.0 requires requests, which is not installed.
Python 3.6.7 (default, Dec 11 2018, 20:49:24) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```

The error message above is `aria2p 0.1.0 requires requests, which is not installed.` written in red. I ran this command in my `aria2p` Python project directory. Is `pipx` reading things in `pyproject.toml` / `poetry.lock` / `*.egg-info` / `dist/` ? I really don't understand what `pipx` is doing here that causes it to output this message :smile:

**Comment by cs01** [comment]
Oh wow that is surprising. No pipx does not read anything local. That command should be operating entirely out of a temporary directory. 

Can you re-run with 
```
pipx --verbose ipython
```

Thanks for reporting!

**Comment by cs01** [comment]
Do you have any environment variables or startup scripts that might be running when Python or pip are invoked?

**Comment by pawamoy** [comment]
> Do you have any environment variables or startup scripts that might be running when Python or pip are invoked?

No!

I re-ran it with `isort` instead of `ipython` (same warning appears):

```console
$ pipx --verbose isort
pipx (run_ephemeral_binary:719): virtualenv is temporary, its location is /tmp/isort_wps9u3v6
pipx (_run:230): running /home/pawamoy/.local/pipx/venvs/pipx-app/bin/python -m venv /tmp/isort_wps9u3v6
pipx (_run:230): running /tmp/isort_wps9u3v6/bin/python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
aria2p 0.1.0 requires requests, which is not installed.
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
pipx (_run:230): running /tmp/isort_wps9u3v6/bin/python -m pip install isort
Collecting isort
  Using cached https://files.pythonhosted.org/packages/1f/2c/22eee714d7199ae0464beda6ad5fedec8fee6a2f7ffd1e8f1840928fe318/isort-4.3.4-py3-none-any.whl
Installing collected packages: isort
Successfully installed isort-4.3.4
pipx (_run:230): running /tmp/isort_wps9u3v6/bin/isort
--- /home/pawamoy/Data/git/pawamoy/aria2p/src/aria2p/client.py:before	2018-12-16 21:10:21.034043
+++ /home/pawamoy/Data/git/pawamoy/aria2p/src/aria2p/client.py:after	2018-12-17 18:21:46.491684
@@ -1,6 +1,6 @@
 import json
+
 import requests
-
 
 DEFAULT_MSG_ID = -1
 
Apply suggested changes to '/home/pawamoy/Data/git/pawamoy/aria2p/src/aria2p/client.py' [y/n/q]? q
```

**Comment by pawamoy** [comment]
Just like in #56, I removed the `egg-info` directory and the warning does not appear anymore. As you said I think it's related to `pip` and not `pipx` :slightly_smiling_face:  Feel free to close both issues!

**Comment by cs01** [comment]
I wonder if it makes sense for pipx to display a warning indicating that the directory name will take precedence over the PyPI package name.

**Comment by pawamoy** [comment]
I don't know how much control you have over `pip`'s internals, but yes, if you can detect this type of situation and display a warning it would be great. Otherwise a simple note in the README/docs/wiki about what happens when there is an `*.egg-info` directory in the current dir could be nice as well.
