### ISSUE TITLE
Unable to install mercurial (requires Python 2.7)

### ISSUE THREAD

**Issue by schinckel** [cs01/pipx#65]
Apparently "Mercurial only supports Python 2.7".

It's not possible to install using `pipx` because `python2 -m venv` does not work.

I don't know if there is a way to make this work, but I think the docs should at least mention that only python3 is supported as an install target.

**Comment by schinckel** [comment]
It took some time for me to discover this was actually the cause, because `pipx` does not show the output from `python setup.py egg_info` if there is an error - `pipsi` does, which showed me when I tried to reinstall there the error.

**Comment by cs01** [comment]
It is already documented here

https://github.com/cs01/pipx#system-requirements

![image](https://user-images.githubusercontent.com/5715368/50940301-39f9b880-1435-11e9-8430-efaf94cdd639.png)

What command did you run? `pipx install mercuriall`? Running `pipx install ... --verbose` will give you all the detail that pipsi has by default.

**Comment by schinckel** [comment]
Aha! I must have missed that.

Yes, `--verbose` shows the output.

I'm happy with that: I'll close the ticket (and hopefully someone else will see it next time if they have a problem installing something).
