### ISSUE TITLE
Pipx uninstall deletes python3 symlink

### ISSUE THREAD

**Issue by sahensley** [cs01/pipx#8]
## Environment Details

I use Pyenv to build my Python distributions then I create a symlink to the binary in ~/.local/bin (which is in $PATH) instead of using the shims.  

For example, I have this symlink in my ~/.local/bin directory:

    python3 -> /Users/username/.pyenv/versions/3.6.6/bin/python3.6

Here's the output of `pipx list` after an install with the default settings:

    venvs are in /Users/username/.local/pipx/venvs, symlinks to binaries are in /Users/username/.local/bin
    package pipx 0.0.0.9, symlinks to binaries available: python3, pipx

## Issue

The issue occurs when I run `pipx uninstall package`.  The command will complete successfully but it also deletes the ~/.local/bin/python3 symlink, which breaks pipx itself and any packages installed.

**Comment by cs01** [comment]
That is strange that it views python3 as a symlink to one of pipx’s binaries. Thanks for reporting, I will get it fixed soon.

**Comment by cs01** [comment]
I was able to reproduce this and fix it. Thanks again for reporting, please share if you run into anything else.
